<?php
/**
  * (c) Redbox Parcel Lockers <thamer@redboxsa.com>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by Redbox Technologies, <thamer@redboxsa.com>
 */

// @codingStandardsIgnoreFile
?>

<script>
    require.config({
        paths: {
            googleMaps: 'https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyBY1xlGe6jLbugOJegCsUGnzlufYWa5CRw&libraries=places',
            MarkerClusterer: 'https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min'
        },
        shim: {
            googleMaps: {
                exports: 'google.maps'
            },
            MarkerClusterer: {
                exports: 'MarkerClusterer'
            }
        }
    });
    window.markerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_redbox.png') ?>';
    window.myMarkerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_my_location.png') ?>';
    window.clusterIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/cluster') ?>';
    window.myLocationIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/my_location.png') ?>';
</script>
<div></div>
