<?php
/**
  * (c) Redbox Parcel Lockers <thamer@redboxsa.com>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by Redbox Technologies, <thamer@redboxsa.com>
 */

// @codingStandardsIgnoreFile
?>

<script>
    var path = {
        MarkerClusterer: 'https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min'
    };
    var shim = {
        MarkerClusterer: {
            exports: 'MarkerClusterer'
        }
    };
    <?php if ($block->isMapActive()) { ?>
        require(['https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyBY1xlGe6jLbugOJegCsUGnzlufYWa5CRw&libraries=places'])
    <?php } ?>
    require.config({
        paths: path,
        shim: shim
    });
    window.markerCounterIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_counter.png') ?>';
    window.markerLockerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_locker.png') ?>';
    window.markerCounterLockerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_counter_locker.png') ?>';
    window.markerSelectedIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_selected.png') ?>';
    window.counterIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/icon_counter.png') ?>';
    window.lockerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/icon_locker.png') ?>';
    window.counterLockerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/icon_counter_locker.png') ?>';
    window.myMarkerIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/marker_my_location.png') ?>';
    window.clusterIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/cluster') ?>';
    window.myLocationIconPath = '<?php /* @noEscape */ echo $block->getViewFileUrl('Redbox_Shipping::images/redbox/my_location.png') ?>';
</script>
<div></div>
