<?php
/**
 * (c) Redbox Parcel Lockers <thamer@redboxsa.com>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by Redbox Technologies, <thamer@redboxsa.com>
 */
?>

<?php if ($block->isInpost()) : ?>
    <p><?php /* @noEscape */ echo __('Once your order is ready to be collected, we\'ll also update you with text and email notification.') ?></p>
<?php endif; ?>
